package com.homepage;

import java.time.Year;
import java.util.List;
import java.util.Vector;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import com.DatabaseCon.DBcon;

import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ferdy
 */
public final class HomeFrame extends javax.swing.JFrame {


    //Inisialisasi 
    String id_book;
    String titles;
    String author;
    String publisher;
    String release_date;
    String isbn;

    public HomeFrame() {
        initComponents();
            this.setResizable(false);
            this.setTableData();
        } 


        public void setTableData(){
            //Membuat objek dari class DefaultTableModel
            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            //Membuat kolom tabel
            model.addColumn("ID");
            model.addColumn("Titles");
            model.addColumn("Author");
            model.addColumn("Publisher");
            model.addColumn("Release Date");
            model.addColumn("ISBN");
    
            //Menambahkan data ke dalam baris baru pada tabel
            try {
                String sql = "SELECT * FROM book_tb";
                java.sql.Connection conn = DBcon.con;
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);

                //Mengambil record dari database dan mendapatkan nya dari book_tb
                while(res.next()){
                    model.addRow(new Object[]{
                        res.getString("id_book"),
                        res.getString("titles"),
                        res.getString("author"),
                        res.getString("publisher"),
                        res.getInt("release_date"),
                        res.getString("isbn")
                    });
                }
                jTableBooks.setModel(model);
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();
        jGetTitleField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jGetAuthorField = new javax.swing.JTextField();
        jGetPublisherField = new javax.swing.JTextField();
        jGetISBNField = new javax.swing.JTextField();
        jInsertBookButton = new javax.swing.JButton();
        jDeleteBookButton = new javax.swing.JButton();
        jUpdateBookButton = new javax.swing.JButton();
        jClearBookButton = new javax.swing.JButton();
        jGetYearField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); 
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/image/book.png"))); 
        jLabel2.setText("BookDB");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTextSearch.setFont(new java.awt.Font("Segoe UI", 2, 12)); 
        jTextSearch.setText("Search by Title/Author/Publisher/Release Date/ISBN");
        jTextSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSearchFocusLost(evt);
            }
        });
        jTextSearch.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTextSearchComponentHidden(evt);
            }
        });
        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });
        jTextSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSearchKeyTyped(evt);
            }
        });

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Publisher", "Release Date", "ISBN"
            }
        ));
        jTableBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBooksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBooks);

        jGetTitleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetTitleFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        jLabel1.setText("Author");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        jLabel4.setText("Publisher");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        jLabel5.setText("Release Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); 
        jLabel6.setText("ISBN");

        jGetAuthorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetAuthorFieldActionPerformed(evt);
            }
        });

        jGetPublisherField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetPublisherFieldActionPerformed(evt);
            }
        });

        jGetISBNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetISBNFieldActionPerformed(evt);
            }
        });

        jInsertBookButton.setBackground(new java.awt.Color(204, 255, 204));
        jInsertBookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); 
        jInsertBookButton.setText("Insert");
        jInsertBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertBookButtonActionPerformed(evt);
            }
        });

        jDeleteBookButton.setBackground(new java.awt.Color(255, 204, 204));
        jDeleteBookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); 
        jDeleteBookButton.setText("Delete");
        jDeleteBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteBookButtonActionPerformed(evt);
            }
        });

        jUpdateBookButton.setBackground(new java.awt.Color(255, 255, 204));
        jUpdateBookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); 
        jUpdateBookButton.setText("Update");
        jUpdateBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateBookButtonActionPerformed(evt);
            }
        });

        jClearBookButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); 
        jClearBookButton.setText("Clear");
        jClearBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearBookButtonActionPerformed(evt);
            }
        });

        jGetYearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGetYearFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextSearch, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jGetAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGetTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jUpdateBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jInsertBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jClearBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jDeleteBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jGetISBNField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jGetYearField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jGetPublisherField, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jTextSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGetTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jGetAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jGetPublisherField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGetYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGetISBNField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDeleteBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(jInsertBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUpdateBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClearBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void jUpdateBookButtonActionPerformed(java.awt.event.ActionEvent evt) {

            String id = id_book; 
            String titles = jGetTitleField.getText();
            String author = jGetAuthorField.getText();
            String publisher = jGetPublisherField.getText();
            int release_date = Integer.parseInt(jGetYearField.getText()); 
            String isbn = jGetISBNField.getText();

            //Membuat objek dari class InsertBook
            InsertBook insertBookObj = new InsertBook(id_book, titles, author, publisher, release_date, isbn);

            //Membuat InsertBookMethod object
            InsertBookMethod insertBookMethod = new InsertBookMethod();
            insertBookMethod.update(insertBookObj);
            setTableData();
    }

    private void jGetISBNFieldActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void jGetPublisherFieldActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void jGetAuthorFieldActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void jGetTitleFieldActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void jTextSearchComponentHidden(java.awt.event.ComponentEvent evt) {
        
    }

    private void jInsertBookButtonActionPerformed(java.awt.event.ActionEvent evt) {

        //Menangkap data yang ada di field ketika melakukan Insert
            String id_book = ""; //
            String titles = jGetTitleField.getText();
            String author = jGetAuthorField.getText();
            String publisher = jGetPublisherField.getText();
            int release_date = Integer.parseInt(jGetYearField.getText()); 
            String isbn = jGetISBNField.getText();

            //Membuat objek dari class InsertBook
            InsertBook insertBookObj = new InsertBook(id_book ,titles, author, publisher, release_date, isbn);

            //Membuat InsertBookMethod object
            InsertBookMethod insertBookMethod = new InsertBookMethod();
            insertBookMethod.insert(insertBookObj);
            setTableData();

    }

    private void jGetYearFieldActionPerformed(java.awt.event.ActionEvent evt) {
        
    }

    private void jClearBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
        jGetTitleField.setText(null);
        jGetAuthorField.setText(null);
        jGetPublisherField.setText(null);
        jGetYearField.setText(null);
        jGetISBNField.setText(null);
    }

    private void jDeleteBookButtonActionPerformed(java.awt.event.ActionEvent evt) {
            String id = id_book;
            String titles = jGetTitleField.getText();
            String author = jGetAuthorField.getText();
            String publisher = jGetPublisherField.getText();
            int release_date = Integer.parseInt(jGetYearField.getText()); 
            String isbn = jGetISBNField.getText();

            //Membuat objek dari class InsertBook
            InsertBook insertBookObj = new InsertBook(id_book, titles, author, publisher, release_date, isbn);

            //Membuat InsertBookMethod object
            InsertBookMethod insertBookMethod = new InsertBookMethod();
            insertBookMethod.delete(insertBookObj);
            setTableData();

            //Mengembalikan Field menjadi null
            jGetTitleField.setText(null);
            jGetAuthorField.setText(null);
            jGetPublisherField.setText(null);
            jGetYearField.setText(null);
            jGetISBNField.setText(null);
    }

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void jTextSearchKeyTyped(java.awt.event.KeyEvent evt) {
        String searchText = jTextSearch.getText().trim();

        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(jTableBooks.getModel());
        jTableBooks.setRowSorter(rowSorter);

        RowFilter<TableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searchText);
        rowSorter.setRowFilter(rowFilter);
    }

    private void jTextSearchFocusLost(java.awt.event.FocusEvent evt) {
        //Mengembalikan teks placeholder jTextSearch ketika tidak ada interaksi
        if(jTextSearch.getText().trim().equals("") || jTextSearch.getText().trim().toLowerCase().equals("search by title/author/publisher/release date/isbn")){
            jTextSearch.setText("Search by Title/Author/Publisher/Release Date/ISBN");
            jTextSearch.setForeground(new java.awt.Color(153,153,153));
        }
    }

    private void jTextSearchFocusGained(java.awt.event.FocusEvent evt) {
        //Menghapus teks placeholder jTextSearch ketika dilakukan interaksi
        if(jTextSearch.getText().trim().toLowerCase().equals("search by title/author/publisher/release date/isbn")){
            jTextSearch.setText("");
            jTextSearch.setForeground(new java.awt.Color(0,0,0));
        }
    }

    private void jTableBooksMouseClicked(java.awt.event.MouseEvent evt) {    
        //Membuat fungsi ketika terdapat interaksi dengan table akan mengisi field yang ada sebelumnya                                     
        int line = jTableBooks.rowAtPoint(evt.getPoint()); //Deklarasi line untuk tabel

        //Mengambil nilai field dan baris yang dipilih dalam jTableBooks dan dikonversi menjadi String
        id_book = jTableBooks.getValueAt(line, 0).toString(); 
        titles = jTableBooks.getValueAt(line, 1).toString();
        author = jTableBooks.getValueAt(line, 2).toString();
        publisher = jTableBooks.getValueAt(line, 3).toString();
        release_date = jTableBooks.getValueAt(line, 4).toString();
        isbn = jTableBooks.getValueAt(line, 5).toString();

        jGetTitleField.setText(titles);
        jGetAuthorField.setText(author);
        jGetPublisherField.setText(publisher);
        jGetYearField.setText(release_date);
        jGetISBNField.setText(isbn);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClearBookButton;
    private javax.swing.JButton jDeleteBookButton;
    private javax.swing.JTextField jGetAuthorField;
    private javax.swing.JTextField jGetISBNField;
    private javax.swing.JTextField jGetPublisherField;
    private javax.swing.JTextField jGetTitleField;
    private javax.swing.JFormattedTextField jGetYearField;
    private javax.swing.JButton jInsertBookButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JButton jUpdateBookButton;
    // End of variables declaration//GEN-END:variables
}
